### ISSUE TITLE
The website is wrongly blank and the "Home" button becomes unusable if you press the "Tab" key after you return to the Homepage UI

### ISSUE THREAD

**Issue by Softvision-CristinaBadescu** [mozilla/tab-split-2#71] opened 2018-03-09 13:08 UTC
[Affected versions]:
- Firefox 58.0.2 and up
- Tab Split 2 0.2.0

[Affected Platforms]:
- All Windows
- All Linux

[Prerequisites]:
- Have a clean Firefox profile with the latest Tab Split 2 v0.2.0 installed.
- Have the Tab Split sidebar open.

[Steps to reproduce]:
1. Open Firefox browser with the profile from prerequisites and navigate to a website.
2. Click the tab from the "Current Tabs" list.
3. Press the "Home" sidebar's button.
4. Click the "Tab" key and press again the "Home" button.

[Expected result]:
- The homepage UI is displayed.

[Actual result]:
- Nothing happens and the website remains blank.

[Notes]:
- This issue is still reproducible if you click the "Refresh" button.
- Here is a screen recording with this issue:
![tab split 2 - home button and blank website](https://user-images.githubusercontent.com/31244235/37208850-8dd662ee-23ab-11e8-9f41-bb4bfa12efa6.gif)

**Comment by ianb** [comment] 2018-03-09 22:41
Duplicate of #63

**Closed by ianb** 2018-03-09 22:41 UTC
