### ISSUE TITLE
New Tab favicon is undefined

### ISSUE THREAD

**Issue by pdehaan** [mozilla/tab-split-2#47] opened 2018-03-01 22:42 UTC
### Steps to reproduce:
1. `npm run run`

### Actual results:
The Tab Split sidebar has a broken image next to the "New Tab" label.

![page_info_-_moz-extension___c7319673-afcd-6d49-a7a3-55e6bf843332_sidebar_html_and_firefox_nightly](https://user-images.githubusercontent.com/557895/36873809-7bef8b58-1d5e-11e8-9c3e-946f22a21380.png)

### Expected results:
Check if the `tab.favIconUrl` is truthy/defined before setting the `image.src` in ./addon/sidebar.js?
Or, possibly set a default favicon, if that keeps the spacing/layout more consistent-ier.

https://github.com/mozilla/tab-split-2/blob/1d839ee41c8be7d37a553fcbd5600893f6b6f2f3/addon/sidebar.js#L22-L23

**Comment by ianb** [comment] 2018-03-01 22:50
Duplicate of #31

**Closed by ianb** 2018-03-01 22:50 UTC
Labels: duplicate
